"""
app.py
-------
Streamlit UI for the AI Hallucination Detector.

Pipeline:
    AI-generated answer
        -> claim_extractor.extract_claims()
        -> retriever.retrieve_evidence() (per claim, over FAISS)
        -> evaluator.evaluate_claim()     (LLM judges claim vs evidence)
        -> scorer.compute_score()         (aggregate reliability score)
"""

import os
import tempfile

import streamlit as st

from claim_extractor import extract_claims
from retriever import build_vector_store, load_documents_from_folder, retrieve_evidence
from evaluator import evaluate_claim
from scorer import compute_score
from llm_provider import provider_name

st.set_page_config(page_title="AI Hallucination Detector", page_icon="🔍", layout="wide")

VERDICT_STYLE = {
    "SUPPORTED": ("✅", "Supported"),
    "CONTRADICTED": ("❌", "Incorrect"),
    "INSUFFICIENT_EVIDENCE": ("⚠️", "Not Enough Evidence"),
}


@st.cache_resource(show_spinner=False)
def load_curated_kb():
    """Load the bundled curated CS knowledge base once per session."""
    docs = load_documents_from_folder("knowledge_base")
    return build_vector_store(docs)


def build_uploaded_kb(uploaded_files):
    """Build a vector store from files the user uploads this session."""
    if not uploaded_files:
        return None
    with tempfile.TemporaryDirectory() as tmp_dir:
        for f in uploaded_files:
            path = os.path.join(tmp_dir, f.name)
            with open(path, "wb") as out:
                out.write(f.getbuffer())
        docs = load_documents_from_folder(tmp_dir)
        return build_vector_store(docs)


def combine_stores(store_a, store_b):
    """Merge two FAISS stores into one, ignoring any that are None."""
    if store_a and store_b:
        store_a.merge_from(store_b)
        return store_a
    return store_a or store_b


# ---------------------------------------------------------------- Sidebar --
with st.sidebar:
    st.header("⚙️ Settings")
    st.caption(f"LLM provider: **{provider_name()}** (set `LLM_PROVIDER` in `.env`)")

    verify_against = st.radio(
        "Verify against",
        ["Computer Science knowledge base", "My uploaded documents", "Both"],
        index=0,
    )

    uploaded_files = None
    if verify_against in ("My uploaded documents", "Both"):
        uploaded_files = st.file_uploader(
            "Upload reference material (.txt, .md, .pdf)",
            type=["txt", "md", "pdf"],
            accept_multiple_files=True,
        )

    top_k = st.slider("Evidence chunks retrieved per claim", 1, 5, 3)

    st.divider()
    st.caption(
        "Reliability score is a heuristic demo metric, not a calibrated "
        "probability of correctness."
    )

# ------------------------------------------------------------------ Main --
st.title("🔍 AI Hallucination Detector")
st.write(
    "Paste an answer generated by ChatGPT, Gemini, Claude, or any other LLM. "
    "This tool breaks it into individual factual claims and checks each one "
    "against a trusted knowledge base."
)

ai_answer = st.text_area(
    "Paste AI-generated answer here",
    height=180,
    placeholder="e.g. Java was invented by Dennis Ritchie in 1985...",
)

analyze_clicked = st.button("Analyze", type="primary")

if analyze_clicked:
    if not ai_answer.strip():
        st.warning("Paste an answer to analyze first.")
        st.stop()

    # ---- Build the right vector store for the chosen mode
    with st.spinner("Preparing knowledge base..."):
        curated_store = None
        uploaded_store = None

        if verify_against in ("Computer Science knowledge base", "Both"):
            curated_store = load_curated_kb()

        if verify_against in ("My uploaded documents", "Both"):
            if not uploaded_files:
                st.warning("Upload at least one document, or switch modes.")
                st.stop()
            uploaded_store = build_uploaded_kb(uploaded_files)

        vector_store = combine_stores(curated_store, uploaded_store)

    # ---- Step 1: claim extraction
    with st.spinner("Extracting claims from the answer..."):
        claims = extract_claims(ai_answer)

    if not claims:
        st.info("No checkable factual claims were found in this answer.")
        st.stop()

    # ---- Step 2 + 3: retrieve evidence and evaluate each claim
    results = []
    progress = st.progress(0.0, text="Verifying claims...")
    for i, claim in enumerate(claims):
        evidence = retrieve_evidence(vector_store, claim, k=top_k)
        result = evaluate_claim(claim, evidence)
        results.append(result)
        progress.progress((i + 1) / len(claims), text=f"Verified claim {i + 1}/{len(claims)}")
    progress.empty()

    # ---- Step 4: aggregate score
    summary = compute_score(results)

    st.divider()
    col1, col2 = st.columns([1, 2])
    with col1:
        st.metric("Overall Reliability", f"{summary.reliability_score}%")
    with col2:
        st.subheader(f"{summary.risk_emoji} {summary.risk_label}")
        st.caption(
            f"{summary.supported_count} supported · "
            f"{summary.contradicted_count} contradicted · "
            f"{summary.insufficient_count} insufficient evidence "
            f"(out of {summary.total_claims} claims)"
        )

    st.divider()
    st.subheader("Claim-by-claim breakdown")

    for i, result in enumerate(results, start=1):
        emoji, label = VERDICT_STYLE[result.verdict]
        with st.container(border=True):
            st.markdown(f"**{emoji} Claim {i} — {label}** (confidence: {result.confidence}%)")
            st.write(f"> {result.claim}")
            st.caption(result.explanation)
            if result.evidence:
                with st.expander("View retrieved evidence"):
                    for j, ev in enumerate(result.evidence, start=1):
                        st.text(f"[{j}] {ev}")
            else:
                st.caption("No relevant evidence was found in the knowledge base.")
